hdfs dfs -mkdir /WS_REMOTE/APTO01
hdfs dfs -mkdir /WS_REMOTE/APTO02
hdfs dfs -mkdir /WS_REMOTE/APTO03
hdfs dfs -mkdir /WS_REMOTE/APTO04
hdfs dfs -mkdir /WS_REMOTE/APTO05
hdfs dfs -mkdir /WS_REMOTE/APTO06
hdfs dfs -mkdir /WS_REMOTE/APTO07
hdfs dfs -mkdir /WS_REMOTE/APTO08
hdfs dfs -mkdir /WS_REMOTE/APTO09
hdfs dfs -mkdir /WS_REMOTE/APTO10
hdfs dfs -mkdir /WS_REMOTE/APTO11
hdfs dfs -mkdir /WS_REMOTE/APTO12
hdfs dfs -mkdir /WS_REMOTE/APTO13
hdfs dfs -mkdir /WS_REMOTE/APTO14
hdfs dfs -mkdir /WS_REMOTE/APTO15
hdfs dfs -mkdir /WS_REMOTE/APTO16
hdfs dfs -mkdir /WS_REMOTE/APTO17
hdfs dfs -mkdir /WS_REMOTE/APTO18
hdfs dfs -mkdir /WS_REMOTE/APTO19
hdfs dfs -mkdir /WS_REMOTE/APTO20
